version: '1.0.0'

sources:
  - name: firebird
    database: SUBWAY
    loader: JDBC  # используется только для документации dbt
  
    tables:
      - name: client
        description: "External table of FireBird client"
        external:
          location: 'jdbc:firebirdsql://anarisuto-firebird:3050/C:\firebird_databases\SUBWAY.FDB'
          options:
            user: SYSDBA
            password: 123