version: '1.0.0'

macros:
  - name: ins_hub_macros
    description: Макрос для вставки md5, которых еще нет
    arguments:
      - name: hub_table
        type: string
        description: Название таблицы хаба в row vault
      - name: source_table
        type: string
        description: название dbt модели, которая является источником для новых md5
      - name: key_join
        type: string
        description: название столбца, в котором хранится md5, то есть rk хаба